export const HANDS_ORDERED = [
  "AA",
  "KK",
  "QQ",
  "JJ",
  "TT",
  "99",
  "AKs",
  "AQs",
  "88",
  "AJs",
  "AKo",
  "KQs",
  "ATs",
  "AQo",
  "77",
  "KJs",
  "A9s",
  "KTs",
  "AJo",
  "KQo",
  "QJs",
  "A8s",
  "66",
  "QTs",
  "ATo",
  "K9s",
  "A7s",
  "KJo",
  "JTs",
  "A5s",
  "A6s",
  "KTo",
  "Q9s",
  "55",
  "A9o",
  "QJo",
  "A4s",
  "K8s",
  "A3s",
  "A8o",
  "K7s",
  "J9s",
  "QTo",
  "A2s",
  "Q8s",
  "K9o",
  "K6s",
  "A7o",
  "T9s",
  "44",
  "JTo",
  "K5s",
  "J8s",
  "A5o",
  "Q7s",
  "A6o",
  "Q9o",
  "K4s",
  "T8s",
  "K3s",
  "K8o",
  "A4o",
  "Q6s",
  "98s",
  "K7o",
  "J7s",
  "K2s",
  "A3o",
  "33",
  "J9o",
  "Q5s",
  "T7s",
  "Q8o",
  "T9o",
  "A2o",
  "K6o",
  "Q4s",
  "J6s",
  "97s",
  "Q3s",
  "J5s",
  "K5o",
  "87s",
  "J8o",
  "22",
  "T6s",
  "Q2s",
  "Q7o",
  "J4s",
  "96s",
  "K4o",
  "T8o",
  "86s",
  "76s",
  "J3s",
  "98o",
  "Q6o",
  "J7o",
  "K3o",
  "T5s",
  "T4s",
  "K2o",
  "J2s",
  "95s",
  "Q5o",
  "T3s",
  "T7o",
  "85s",
  "65s",
  "Q4o",
  "75s",
  "J6o",
  "T2s",
  "97o",
  "94s",
  "87o",
  "Q3o",
  "93s",
  "54s",
  "84s",
  "J5o",
  "64s",
  "T6o",
  "74s",
  "Q2o",
  "92s",
  "J4o",
  "53s",
  "96o",
  "86o",
  "76o",
  "73s",
  "83s",
  "63s",
  "J3o",
  "T5o",
  "82s",
  "43s",
  "J2o",
  "T4o",
  "95o",
  "52s",
  "62s",
  "72s",
  "85o",
  "65o",
  "75o",
  "T3o",
  "42s",
  "32s",
  "T2o",
  "94o",
  "54o",
  "84o",
  "64o",
  "93o",
  "74o",
  "92o",
  "53o",
  "83o",
  "63o",
  "73o",
  "43o",
  "82o",
  "52o",
  "62o",
  "72o",
  "42o",
  "32o",
] as const;
export const RANKS = ["A", "K", "Q", "J", "T", "9", "8", "7", "6", "5", "4", "3", "2"] as const;
export const SUITS = ["s", "h", "c", "d"] as const;

export const SIX_MAX_OPEN = {
  UTG: "44+, A2s+, K9s+, Q9s+, J9s+, T9s, 98s, 87s, 76s, ATo+, KJo+",
  "UTG+1": "22+, A2s+, K8s+, Q9s+, J9s+, T9s, 98s, 87s, 76s, 65s, 54s, ATo+, KTo+, QJo, JTo",
  Cutoff:
    "22+, A2s+, K6s+, Q8s+, J8s+, T8s+, 97s+, 86s+, 75s+, 65s, 54s, 43s, 32s, A8o+, A5o, KTo+, QTo+, JTo, T9o, 98o",
  Button:
    "22+, A2s+, K2s+, Q4s+, J6s+, T6s+, 95s+, 85s+, 74s+, 63s+, 53s+, 43s, 32s, A2o+, K7o+, Q9o+, J9o+, T9o, 98o",
  "Small Blind":
    "22+, A2s+, K2s+, Q3s+, J4s+, T4s+, 94s+, 84s+, 73s+, 63s+, 53s+, 43s, 32s, A2o+, K4o+, Q8o+, J9o+, T9o, 98o",
};

export const NINE_MAX_OPEN = {
  UTG: "77+, ATs+, A5s, KTs+, QTs+, J9s+, T9s, 98s, AQo+",
  "UTG+1": "77+, ATs+, A5s, KTs+, QTs+, J9s+, T9s, 98s, AQo+",
  "UTG+2": "77+, A8s+, A4s-A5s, K9s+, Q9s+, J9s+, T9s, 98s, AJo+",
  Lojack: "44+, A2s+, K9s+, Q9s+, J9s+, T9s, 98s, 87s, 76s, ATo+, KJo+",
  Hijack: "22+, A2s+, K8s+, Q9s+, J9s+, T9s, 98s, 87s, 76s, 65s, 54s, ATo+, KTo+, QJo, JTo",
  Cutoff:
    "22+, A2s+, K6s+, Q8s+, J8s+, T8s+, 97s+, 86s+, 75s+, 65s, 54s, 43s, 32s, A8o+, A5o, KTo+, QTo+, JTo, T9o, 98o",
  Button:
    "22+, A2s+, K2s+, Q4s+, J6s+, T6s+, 95s+, 85s+, 74s+, 63s+, 53s+, 43s, 32s, A2o+, K7o+, Q9o+, J9o+, T9o, 98o",
  "Small Blind":
    "22+, A2s+, K2s+, Q3s+, J4s+, T4s+, 94s+, 84s+, 73s+, 63s+, 53s+, 43s, 32s, A2o+, K4o+, Q8o+, J9o+, T9o, 98o",
};

export const METERS = [
  "straightflush",
  "quads",
  "fullhouse",
  "flush",
  "straight",
  "trips",
  "set",
  "twopair",
  "pair",
  "overpair",
  "toppair",
  "secondpair",
  "weakpair",
  "highcard",
  "acehigh",
  "flushdraw",
  "flushdraw_pair",
  "flushdraw_oesd",
  "flushdraw_gutshot",
  "backdoorflushdraw",
  "oesd",
  "oesd_pair",
  "gutshot",
  "gutshot_pair",
  "gutshot_overcards",
  "overcards",
] as const;

export const QUALIFIERS = [
  "straightflush",
  "quads",
  "fullhouse",
  "flush",
  "straight",
  "trips",
  "twopair",
  "pair",
  "highcard",
  "flushdraw",
  "backdoorflushdraw",
  "oesd",
  "gutshot",
  "overcards",
] as const;

export const SUBQUALIFIERS = {
  trips: ["set"],
  pair: ["overpair", "toppair", "secondpair", "weakpair"],
  highcard: ["acehigh"],
  flushdraw: ["flushdraw_pair", "flushdraw_oesd", "flushdraw_gutshot"],
  oesd: ["oesd_pair"],
  gutshot: ["gutshot_pair", "gutshot_overcards"],
};

export const QUALIFIER_DISPLAY = {
  straightflush: "Straight Flush",
  quads: "Quads",
  fullhouse: "Full House",
  flush: "Flush",
  straight: "Straight",
  trips: "Trips",
  set: "Set",
  twopair: "Two Pair",
  pair: "Pair",
  overpair: "Overpair",
  toppair: "Top Pair",
  secondpair: "Second Pair",
  weakpair: "Weak Pair",
  highcard: "High Card",
  acehigh: "Ace High",
  flushdraw: "Flush Draw",
  flushdraw_pair: "Flush Draw + Pair",
  flushdraw_oesd: "Flush Draw + OESD",
  flushdraw_gutshot: "Flush Draw + Gutshot",
  backdoorflushdraw: "Backdoor Flush Draw",
  oesd: "OESD",
  oesd_pair: "OESD + Pair",
  gutshot: "Gutshot",
  gutshot_pair: "Gutshot + Pair",
  gutshot_overcards: "Gutshot + Overcards",
  overcards: "Overcards",
};

export const SUITS_TO_HTML = {
  s: "♠",
  c: "♣",
  d: "♦",
  h: "♥",
  x: "□",
};

export const ROUNDS = ["preflop", "flop", "turn", "river"] as const;
export const ROUNDS_DISPLAY = {
  preflop: "Pre-flop",
  flop: "Flop",
  turn: "Turn",
  river: "River",
};

export const COLORS = {
  purple: ["#BBABE2", "#916FE2"],
  blue: ["#90D5EC", "#31B5FF"],
  green: ["#90EE90", "#4CD44C"],
  yellow: ["#FFE7AC", "#FFC107"],
  red: ["#EFACB3", "#FF3344"],
};
