interface Qualifiers {
  straightflush: boolean;
  quads: boolean;
  fullhouse: boolean;
  flush: boolean;
  straight: boolean;
  trips: boolean;
  set: boolean;
  twopair: boolean;
  pair: boolean;
  overpair: boolean;
  toppair: boolean;
  secondpair: boolean;
  weakpair: boolean;
  highcard: boolean;
  acehigh: boolean;
  flushdraw: boolean;
  flushdraw_pair: boolean;
  flushdraw_oesd: boolean;
  flushdraw_gutshot: boolean;
  backdoorflushdraw: boolean;
  oesd: boolean;
  oesd_pair: boolean;
  gutshot: boolean;
  gutshot_pair: boolean;
  gutshot_overcards: boolean;
  overcards: boolean;
}

export interface SelectedQualifiers {
  flop: Qualifiers;
  turn: Qualifiers;
  river: Qualifiers;
}

export const SELECTED_QUALIFIERS_DEFAULT: SelectedQualifiers = {
  flop: {
    straightflush: true,
    quads: true,
    fullhouse: true,
    flush: true,
    straight: true,
    trips: true,
    set: true,
    twopair: true,
    pair: true,
    overpair: true,
    toppair: true,
    secondpair: true,
    weakpair: true,
    highcard: true,
    acehigh: true,
    flushdraw: true,
    flushdraw_pair: true,
    flushdraw_oesd: true,
    flushdraw_gutshot: true,
    backdoorflushdraw: true,
    oesd: true,
    oesd_pair: true,
    gutshot: true,
    gutshot_pair: true,
    gutshot_overcards: true,
    overcards: true,
  },
  turn: {
    straightflush: true,
    quads: true,
    fullhouse: true,
    flush: true,
    straight: true,
    trips: true,
    set: true,
    twopair: true,
    pair: true,
    overpair: true,
    toppair: true,
    secondpair: true,
    weakpair: true,
    highcard: true,
    acehigh: true,
    flushdraw: true,
    flushdraw_pair: true,
    flushdraw_oesd: true,
    flushdraw_gutshot: true,
    backdoorflushdraw: false,
    oesd: true,
    oesd_pair: true,
    gutshot: true,
    gutshot_pair: true,
    gutshot_overcards: true,
    overcards: true,
  },
  river: {
    straightflush: true,
    quads: true,
    fullhouse: true,
    flush: true,
    straight: true,
    trips: true,
    set: true,
    twopair: true,
    pair: true,
    overpair: true,
    toppair: true,
    secondpair: true,
    weakpair: true,
    highcard: true,
    acehigh: true,
    flushdraw: false,
    flushdraw_pair: false,
    flushdraw_oesd: false,
    flushdraw_gutshot: false,
    backdoorflushdraw: false,
    oesd: false,
    oesd_pair: false,
    gutshot: false,
    gutshot_pair: false,
    gutshot_overcards: false,
    overcards: false,
  },
};
